version: '3.3'
services:
  health-check:
    build: .
    restart: always
    volumes:
      - ./logs:/app/logs
    secrets:
      - health_check_secrets

secrets:
  health_check_secrets:
      file: ./secrets